### ISSUE TITLE
20240808  第一个 PR，第一次给 Kubernetes 开源社区做贡献！

### ISSUE THREAD

**Issue by cyy8** [cyy8/notes#2]
今天是学习 IT 技术的第20天，开始了解 K8s 的第一天，浏览了官方文档，并提了一个小小的PR。

这也是我第一次提交 Pull Request 啊，第一次给开源社区做贡献!

https://github.com/kubernetes/website/pull/47399

Welcome @cyy8!
It looks like this is your first PR to kubernetes/website 🎉.
…
Thank you, and welcome to Kubernetes.

**Comment by yikZero** [comment]
欢迎来到开源社区，祝你成功👏

Welcome to Open source community! Good luck 👏!

**Comment by qiyh99** [comment]
逆天了 提交个空格 哗众取宠是吧

**Comment by HyperClockUp** [comment]
🤣👉🏻🤡

**Comment by B1F030** [comment]
> 逆天了 提交个空格 哗众取宠是吧

就事论事，这里的提交确实并非无意义的空行。
===
- [原文档](https://kubernetes.io/docs/reference/kubectl/docker-cli-to-kubectl/#docker-run)中有问题的部分：
<img width="969" alt="image" src="https://github.com/user-attachments/assets/638f6739-2bfd-45c8-9519-b3a0ffa302f5">

- 下面类似的部分：
<img width="967" alt="image" src="https://github.com/user-attachments/assets/5a8b3e92-1941-4712-b46d-0ae6edb83797">

另外补充一些我的看法：

我觉得对于英语专业的人来说，参与开源，贡献一些文档翻译是很合适的，很多项目的文档都缺少专人维护。但这里的标题确实很有争议，对于年龄较大自称转码的人而言，上手就贡献 k8s 是很夸张的事，结果大家一看就是改了一处文档，只会让大家觉得你是在引流炒作。

贡献一个空行，确实算是参与了开源。开源本就没有什么门槛，任何人都可以从最简单的文档贡献开始，有代码基础的人可以从测试用例、修复 bug 开始，逐步参与到 feature、review，成为项目 member 以至于 maintainer。

但贡献一个空行，也很难说是“转码”，大家普遍认知中对 k8s 的贡献，大概率是代码方面的贡献，比如修复一个小 bug。如果你甚至没有写过代码，很难说你是“转码给 k8s 做贡献“。

给 k8s 贡献是一件很有成就感的事，但成就感和虚荣感的边界本就比较模糊，我永远可以装作自己很厉害，给知名开源大项目做贡献，但是装得久了，你是否真的有成长，是很重要的事，骗得过别人，骗不过心虚的自己。

现在信息这么发达，各种教程网上都有，转码也已经不算什么难事，只要你真的有这份毅力，我相信你可以做到，但保持一个谦虚学习的心态，也是很重要的事。

能发现这一处格式错误并将其修正，是你实打实的能力。希望你继续坚持参与开源，但很多时候为了贡献文档，也需要你对这个功能有充分的了解，慢慢地你可以从文档到代码，再到架构，我就认识不止一个人经历了这样的成长路线。

**Comment by game118** [comment]
这次修改提升了可读性。

**Comment by LasFoacs** [comment]
修改文档不失为一种开始，如果觉得发小红书有不妥应该去给小红书点踩，而不是在这里或者给PR点踩。

**Comment by Just-Prog** [comment]
建议即刻入职华为，为开源项目 fix typo 率添砖加瓦

**Comment by LouisLiu00** [comment]
Good job! lmao

**Comment by gaoziman** [comment]
> 今天是学习 IT 技术的第20天，开始了解 K8s 的第一天，浏览了官方文档，并提了一个小小的PR。
> 
> 这也是我第一次提交 Pull Request 啊，第一次给开源社区做贡献!
> 
> [kubernetes/website#47399](https://github.com/kubernetes/website/pull/47399)
> 
> Welcome @cyy8! It looks like this is your first PR to kubernetes/website 🎉. … Thank you, and welcome to Kubernetes.

小姐姐好厉害，祝贺你，继续努力，早日成为IT大牛。

**Comment by tw358** [comment]
good

**Comment by forever-z-133** [comment]
挺有意思的，加油～

**Comment by delbertbeta** [comment]
加油！

**Comment by snstaberah** [comment]
加油！

**Comment by yxb1987** [comment]
弱弱的问句，小仙女姐姐在学什么方向的it，是运维工程师吗？

**Comment by yanxu4780** [comment]
别学运维了，哪天不小心再把生产库，或者docker镜像给删了。学学前端算了。

**Comment by sheldonhu** [comment]
k8s做到今天，离不开贡献者的每一次pr。

**Comment by boogieLing** [comment]
> 修改文档不失为一种开始，如果觉得发小红书有不妥应该去给小红书点踩，而不是在这里或者给PR点踩。

少偷换概念了，"修改文档不失为一种开始"，是一种开始但很难说是一种“好的开始”，更不是原po所说的”给开源社区做贡献!“了，没人说这是给开源社区拉屎就不错了。另外后面那句”而不是在这里或者给PR点踩“，发都发在github了，不来github难道去小红书讨论，如果不能接受什么叫真正的开源共建，那应该让原po滚回小红书发，而不是在开源社区拉屎之后又不允许别人拒绝闻屎。

**Comment by NorthSecond** [comment]
*还是希望开源社区有更多新鲜血液的加入，在贡献开源的过程中提交自己，一步步从 typo 到更深层次的修改，Build the World from Opensource together.*

**Comment by AiraNadih** [comment]
> > 逆天了 提交个空格 哗众取宠是吧
> 
> # 就事论事，这里的提交确实并非无意义的空行。
> 
>     * [原文档](https://kubernetes.io/docs/reference/kubectl/docker-cli-to-kubectl/#docker-run)中有问题的部分：
> 
> 
> <img alt="image" width="969" src="https://private-user-images.githubusercontent.com/77265354/356509622-638f6739-2bfd-45c8-9519-b3a0ffa302f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTc1NTIsIm5iZiI6MTcyMzE5NzI1MiwicGF0aCI6Ii83NzI2NTM1NC8zNTY1MDk2MjItNjM4ZjY3MzktMmJmZC00NWM4LTk1MTktYjNhMGZmYTMwMmY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA5NTQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwNmIxMGY0NjFmZTBhMmEyN2FiZThhMDcxNTMyNDFlYmE5YWJkNGZlMDE2YjIxM2FiOWViYTI2ZWI3MGJlYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.onLlrVGkzixpzHlnHqwS8qNJeJlsc0zpzwH6dVAwQOk">
> 
>     * 下面类似的部分：
> 
> 
> <img alt="image" width="967" src="https://private-user-images.githubusercontent.com/77265354/356509831-5a8b3e92-1941-4712-b46d-0ae6edb83797.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTc1NTIsIm5iZiI6MTcyMzE5NzI1MiwicGF0aCI6Ii83NzI2NTM1NC8zNTY1MDk4MzEtNWE4YjNlOTItMTk0MS00NzEyLWI0NmQtMGFlNmVkYjgzNzk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA5NTQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhYTFjZWIyZThkMDQxZGMyOWU4YmY1NzA0ODkzMThmODc1MzhmNjY4MzY0YTQ4MTAzYTJlYjcwY2ExNzdjMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SO8eacB6jcPLyno9s0yRMepEZi8LpbxqAmhqLwV1VYU">
> # 另外补充一些我的看法，大家都是看到这张图过来的吧：
> 
> ![image](https://private-user-images.githubusercontent.com/77265354/356510468-17980cc0-3490-4eca-b167-053a13e804ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTc1NTIsIm5iZiI6MTcyMzE5NzI1MiwicGF0aCI6Ii83NzI2NTM1NC8zNTY1MTA0NjgtMTc5ODBjYzAtMzQ5MC00ZWNhLWIxNjctMDUzYTEzZTgwNGNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA5NTQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmNDNmN2RkNzI2OTg4YTY5NGFkM2VhMzRmZTFmYzZiODcyNTU5M2EzYTY4MjM1ZmE2ODU0MjM3ZTYxMjkzMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WAutO-LoKELHFbsB34qnNMtsPK7IsOR4-PmJaJW3SsM)
> 
> 我觉得对于英语专业的人来说，参与开源，贡献一些文档翻译是很合适的，很多项目的文档都缺少专人维护。但这里的标题确实很有争议，对于年龄较大自称转码的人而言，上手就贡献 k8s 是很夸张的事，结果大家一看就是改了一处文档，只会让大家觉得你是在引流炒作。
> 
> 贡献一个空行，确实算是参与了开源。开源本就没有什么门槛，任何人都可以从最简单的文档贡献开始，有代码基础的人可以从测试用例、修复 bug 开始，逐步参与到 feature、review，成为项目 member 以至于 maintainer。
> 
> 但贡献一个空行，也很难说是“转码”，大家普遍认知中对 k8s 的贡献，大概率是代码方面的贡献，比如修复一个小 bug。如果你甚至没有写过代码，很难说你是“转码给 k8s 做贡献“。
> 
> 给 k8s 贡献是一件很有成就感的事，但成就感和虚荣感的边界本就比较模糊，我永远可以装作自己很厉害，给知名开源大项目做贡献，但是装得久了，你是否真的有成长，是很重要的事，骗得过别人，骗不过心虚的自己。
> 
> 现在信息这么发达，各种教程网上都有，转码也已经不算什么难事，只要你真的有这份毅力，我相信你可以做到，但保持一个谦虚学习的心态，也是很重要的事。
> 
> 能发现这一处格式错误并将其修正，是你实打实的能力。希望你继续坚持参与开源，但很多时候为了贡献文档，也需要你对这个功能有充分的了解，慢慢地你可以从文档到代码，再到架构，我就认识不止一个人经历了这样的成长路线。

我的看法是，要么用 markdown lint 弄彻底些，否则就加一个空行毫无意义。

**Comment by Okabe-Rintarou-0** [comment]
强烈建议小姐姐速成k8s之后学习 [istio](https://istio.io/latest/docs/ambient/getting-started/)，毕竟这么擅长流量治理😂。

**Comment by hotstar-xia** [comment]
她发的时候也没想着会火吧

**Comment by fakecore** [comment]
在我看来这本身的修改就是对于人力的浪费, 另外加上在小红书分享, 很难不让人联想到这是一个作秀行为.
如果真想贡献, 请做bug fix 或者 文档翻译, 而不是这里找空格错误🙅

**Comment by y4code** [comment]
> 别学运维了，哪天不小心再把生产库，或者docker镜像给删了。学学前端算了。

前端怎么你了 😅 
别骂了 😭

**Comment by sitjac** [comment]
别拿 typo 不当 pr，红红火火呼呼

**Comment by voldikss** [comment]
FYI https://github.com/kubernetes/website/pull/47399/files

**Comment by voldikss** [comment]
https://github.com/kubernetes/website/pull/47399/files

**Comment by MathildaStacy** [comment]
你真是个逆天

**Comment by LancerComet** [comment]
What a stupid Chinese girl, who was trying to hype herself as a computer science master.

**Comment by pacoxu** [comment]
@cyy8 Congratulations! 👏👍 
Thanks for the contribution to Kubernetes community, and https://github.com/kubernetes/website/pull/47399 solve a real problem. 

For future contributions, you can refer to Natali 's suggestion https://github.com/kubernetes/website/pull/47414#issuecomment-2277646230, and you can also refer to https://www.kubernetes.dev/ for more information. For Chinese version, you may refer to https://github.com/DaoCloud-OpenSource/docs/blob/main/kubernetes/KubernetesDeveloperHandbook.md. 

---
To others

- before you comments in an opensource community, please read the code of conduct of CNCF https://github.com/cncf/foundation/blob/main/code-of-conduct-languages/zh.md. 

> As contributors, maintainers, and participants in the CNCF community, and in the interest of fostering an open and welcoming community, we pledge to respect all people who participate or contribute through reporting issues, posting feature requests, updating documentation, submitting pull requests or patches, attending conferences or events, or engaging in other community or project activities.
> 作为 CNCF 社区的贡献者、维护者和参与者，为了培养一个开放和热情的社区，我们承诺尊重所有通过报告问题、发布功能请求、更新文档、提交拉取请求或补丁、参加会议或活动或参与其他社区或项目活动来参与或贡献的人。

For short, be kind to each other.

https://github.com/cncf/foundation/blob/2a58de4421a73db2c72f4ebe0795d8533ad1901e/code-of-conduct.md?plain=1#L47-L73

---

P.S.: I appreciate your contribution and encourage you to keep up the great work! Your efforts make a real difference in the community. I also invite anyone interested to join and contribute to our vibrant Kubernetes community. Welcome everyone to the Kubernetes community!

**Comment by AiraNadih** [comment]
建议你用 markdown lint 好好完善那个 PR

**Comment by yigekuyou** [comment]
我不太懂md格式，所以那个md就只有一个空行错误吗？

**Comment by gowk** [comment]
来凑个热闹，转码就好好学，整这些哗众取宠的玩意真他妈的丢人

**Comment by Okabe-Rintarou-0** [comment]
pr还真没问题。

**Comment by galaxy-sea** [comment]
这波我站在菜鸟这边，未来持续关注楼主，留个楼。

**Comment by jyz0309** [comment]
Congratulations! 👏 I think it's worth submitting a PR if it can improve the quality of the repo (whether it's code or doc). Welcome to Open source community!

**Comment by jarvie-mei** [comment]
Github is not a place for idle gossip or inciting conflict. show some respect please.

**Comment by coalooball** [comment]
这个标题为什么不标明 typo，标题要规范。

**Comment by Wesley-Young** [comment]
孩子你无敌了

**Comment by Pateo-zhengfang** [comment]
小红书已经10万+了  666

**Comment by yxxhero** [comment]
> What a stupid Chinese girl, who was trying to hype herself as a computer science master.

please be kind. thanks so much.

**Comment by xiaojia21190** [comment]
希望将来能听到你对开源的其他贡献， 加油！！！！ @cyy8

**Comment by jiqing112** [comment]
脑残

**Comment by WhitePhosphor** [comment]
孩子你无敌了🤗🤗🤗

**Comment by yanghuilong** [comment]
> 
> <img alt="image" width="969" src="https://private-user-images.githubusercontent.com/77265354/356509622-638f6739-2bfd-45c8-9519-b3a0ffa302f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNjk2NTcsIm5iZiI6MTcyMzI2OTM1NywicGF0aCI6Ii83NzI2NTM1NC8zNTY1MDk2MjItNjM4ZjY3MzktMmJmZC00NWM4LTk1MTktYjNhMGZmYTMwMmY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDA1NTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZTczMGNmNWYzYjEzOTkxYmU4MzczMTFmMWVmYjFiMjYxNDk3ODE5NzIxNWZhZTc4ODAwZjM1NTVmMzk5YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B3jEQBZ58GrbxJsTRjrjtTVsvo_mdFyMGmM2CIOp0_E">
> * 下面类似的部分：
> 
> <img alt="image" width="967" src="https://private-user-images.githubusercontent.com/77265354/356509831-5a8b3e92-1941-4712-b46d-0ae6edb83797.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNjk2NTcsIm5iZiI6MTcyMzI2OTM1NywicGF0aCI6Ii83NzI2NTM1NC8zNTY1MDk4MzEtNWE4YjNlOTItMTk0MS00NzEyLWI0NmQtMGFlNmVkYjgzNzk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDA1NTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkZTM5M2M2NDlmYjFlMDIyNzBhMDYyYWEyMjEwNGFjOWVhMGQwZTgwMGJiNDFlYjY1OTA1YTcwY2NhNTQwYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e6qWuJzmBiW_n9sBhuRm5QCZxHsAgdIh5zgPe6ZcrVo">
> # 另外补充一些我的看法，大家都是看到这张图过来的吧：
> ![image](https://private-user-images.githubusercontent.com/77265354/356510468-17980cc0-3490-4eca-b167-053a13e804ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNjk2NTcsIm5iZiI6MTcyMzI2OTM1NywicGF0aCI6Ii83NzI2NTM1NC8zNTY1MTA0NjgtMTc5ODBjYzAtMzQ5MC00ZWNhLWIxNjctMDUzYTEzZTgwNGNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDA1NTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MTU5OGZlZjE2OTAwZWQ3MDNmNDJlYmQyNTU4MmE0NTZiMTZmZGUzZDc2MmYyNjljZWZiMWJiNjQzY2M3ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6_W0NhlN5d1yWqlRJRqxKqnEdvHT5gCnSNVlaJHbfVI)
> 
> 我觉得对于英语专业的人来说，参与开源，贡献一些文档翻译是很合适的，很多项目的文档都缺少专人维护。但这里的标题确实很有争议，对于年龄较大自称转码的人而言，上手就贡献 k8s 是很夸张的事，结果大家一看就是改了一处文档，只会让大家觉得你是在引流炒作。
> 
> 贡献一个空行，确实算是参与了开源。开源本就没有什么门槛，任何人都可以从最简单的文档贡献开始，有代码基础的人可以从测试用例、修复 bug 开始，逐步参与到 feature、review，成为项目 member 以至于 maintainer。
> 
> 但贡献一个空行，也很难说是“转码”，大家普遍认知中对 k8s 的贡献，大概率是代码方面的贡献，比如修复一个小 bug。如果你甚至没有写过代码，很难说你是“转码给 k8s 做贡献“。
> 
> 给 k8s 贡献是一件很有成就感的事，但成就感和虚荣感的边界本就比较模糊，我永远可以装作自己很厉害，给知名开源大项目做贡献，但是装得久了，你是否真的有成长，是很重要的事，骗得过别人，骗不过心虚的自己。
> 
> 现在信息这么发达，各种教程网上都有，转码也已经不算什么难事，只要你真的有这份毅力，我相信你可以做到，但保持一个谦虚学习的心态，也是很重要的事。
> 
> 能发现这一处格式错误并将其修正，是你实打实的能力。希望你继续坚持参与开源，但很多时候为了贡献文档，也需要你对这个功能有充分的了解，慢慢地你可以从文档到代码，再到架构，我就认识不止一个人经历了这样的成长路线。


> 今天是学习 IT 技术的第20天，开始了解 K8s 的第一天，浏览了官方文档，并提了一个小小的PR。
> 
> 这也是我第一次提交 Pull Request 啊，第一次给开源社区做贡献!
> 
> [kubernetes/website#47399](https://github.com/kubernetes/website/pull/47399)
> 
> Welcome @cyy8! It looks like this is your first PR to kubernetes/website 🎉. … Thank you, and welcome to Kubernetes.



能不能不要浪费别人和review ,merge 代码的时间. 你时间多, 维护人员难道和你时间一样多吗, 所有人都像你一样去提交一个空格和换行有什么意义, 完全是哗众取宠. 浪费时间.

**Comment by clansty** [comment]
都已经决定学计算机了，就应该把小红书这样的垃圾平台卸载，影响智力

**Comment by ziniuguo** [comment]
> 逆天了 提交个空格 哗众取宠是吧

给你支完了

**Comment by Irving2020** [comment]
人家维护社区挺忙的 不给你合并还打消社区人员积极性... 就别给人家添乱了孩子...

**Comment by NorthSecond** [comment]
提醒一下，首先，删除 comment 在 issue 的时间线上是会留下痕迹的；其次，issue 参与者的邮箱邮件也都有记录。

![image](https://github.com/user-attachments/assets/4b539bc5-10da-46d3-af18-205b23986e50)

我想说什么呢？开源社区欢迎每一位对于技术有热情，有能力贡献的参与者；大家无偿地加入开源社区无非也就图一个成就感什么的，所以发小红书这种我个人也觉得没什么。但是问题在于，我发现你删除了 @AiraNadih 建议你使用 [markdownlint](https://github.com/markdownlint/markdownlint) 刷一下的相对来说属于技术建议的 comment，留下的都是各种没有营养的争论。

如果你认为自媒体上的流量或者主观的情绪价值要比客观的技术重要的话，我建议你趁早放弃转行。工科在专业上没有人情味可以讲的，项目不会因为你 emo 了为了给你提供情绪价值而自动帮你修 bug 的。我觉得你现在需要思考的是自己的目标是什么，为了达到这个目标学习路线和途径是什么，现在自己有哪些基础知识，还差什么。先理清楚自己要学什么然后真正能够投入进自己所想要学习的内容里吧。

转码不难，但是这个话是在工科里面说的，近年来新进大厂的所谓“越老越吃香”的资深高薪的云原生or虚拟化的工程师，看着非常光鲜亮丽，谁手底下没认认真真写过几万行甚至是几万行代码的？

**Comment by cyy8** [comment]
Thanks a lot for your comments. 
Deleted or edited some unfriendly comments.
Please be kind to each other.

**Comment by otakutyrant** [comment]
看到一些对开源社区有毒的言论。有人说这是浪费人力，我写了脚本统计 git 项目里改动行数不超过五个的 commits 数量：

```
import subprocess

THRESHOLD = 5

def count_trivia_commit():
    trivia_commit = 0
    with open("commits.txt", "r") as f: # 我先前 git log 输出所有 commits 到这文件里
        lines = f.readlines()
    for line in lines:
        commit_hash = line.strip()
        try:
            diff_output = subprocess.check_output(["git", "diff", "--numstat", f"{commit_hash}^..{commit_hash}"]).decode()
        except subprocess.CalledProcessError: # 有时 commit 的 父提交不存在从而出错，直接跳过。
            pass
        else:
            # 解析 diff 信息，统计改动行数
            count = 0
            for line in diff_output.splitlines():
                if line.strip():
                    added, deleted, *_ = line.split()
                    if added != '-' and deleted != '-':
                        count = count + int(added) + int(deleted)
                if count > THRESHOLD:
                    break
            else:
                message = subprocess.check_output(["git", "show", "--pretty=format:%s", f"{commit_hash}"]).decode()
                if "Merge pull request" in message:
                    print(commit_hash)
                    print(message)
                    trivia_commit += 1

    print("小小贡献的数量", trivia_commit)

if __name__ == "__main__":
    count_trivia_commit()
```

在 kubernetes/website 跑了几分钟，统计出小小贡献的数量有 5843 个，调整阈值为 1 的话则有 535 个。本来一个 PR 有没有价值是官方开发者说了算，既然官方已经合并这么多了小小的 PR，可以知道哪怕只改一行的 PR 也是很有意义的。OP 的 PR 已经有三人 approve 了。

还有人指责 OP 在小红书标题党，说到底在这些人的法眼里怕是只有对核心项目的深度参与才算「对开源社区的贡献」，在 issues 交流，在 reddit 解答问题，改文档等就不算「对开源社区的贡献」了。这样的指责对开源社区有建设性吗？

还有些人在原 PR 引入了大量信息噪声，甚至直接用华语，对官方开发者又何尝不是困扰呢？官方也 lock 掉讨论了。想象下官方以往在合并 535 个改动只有一行的 PR 的同时还要面对这样的信息噪声，会什么样。

总的来说 OP 没有做错，真正对开源社区有毒的是那一些指责者。

**Comment by NorthSecond** [comment]
In fact, your so-called "edited" completely changed the original meaning of the comment. I think this issue is no longer worth discussing. If you think that social media data and recognition are more important than what you actually learn, then I wish you a better future lol.
在 Aug 10, 2024, 6:38 PM +0800，cyy8 ***@***.***>，写道：

**Comment by Zxis233** [comment]
可以理解的，毕竟大部分的新手第一个PR都是Typo。希望之后能看到你有更多技术层面的PR！

**Comment by cyy8** [comment]
Thanks again,   I will keep learning and contributing to open source community.

**Comment by tcdw** [comment]
没有人不是从萌新阶段走过来的。加油！

**Comment by lmk123568** [comment]
看了xhs，觉得你爱秀，来这里看了pr，好像你这个也没啥问题。

怎么说呢，现在不喷你了，鼓励你继续走下去，假如你32岁文科真的转码成功了，确实值得xhs炫耀，这算是一个正向积极榜样了。

最后说一句，尊重是靠实力换来的，大龄文科转码后xhs狠狠打他们脸

**Comment by HyperClockUp** [comment]
不好的评论你会删是吧🤣👉🤡

**Comment by TheKonka** [comment]
就事论事，pr没问题，我发现这里的排版错误说不定我也会提，何况这是别人第一次给开源社区提pr，值得鼓励才是

**Comment by xx10n31y** [comment]
readme工程师/typo工程师
